name: PROD Deploy Stub

on:
  workflow_dispatch:
  push:
    branches: [prod]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    steps:
      - run: echo "Stub workflow — visible in UI; runs only on prod"
